name: rnwf_downloader

on:
  workflow_dispatch:

jobs:
  download_data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Create Data Folder
      run: |
        mkdir -p rnwf_data/$(date +%Y-%m-%d)
      working-directory: ${{ github.workspace }}

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.2

    - name: Install Python Dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ${{ github.workspace }}

    - name: Execute Notebook
      run: |
        ipython -c "%run code/request_rnwf.ipynb"
      working-directory: ${{ github.workspace }}

    - name: Move CSV File to Data Folder
      run: |
        mv rhwf.csv rnwf_data/$(date +%Y-%m-%d)/
      working-directory: ${{ github.workspace }}

