name: rnwf_downloader

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  download_data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install python and requirements
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.2
    - run: pip install -r requirements.txt

    - name: Create date folder
      run: |
        mkdir -p rnwf_data/$(date +%Y-%m-%d)

    - name: Execute notebook
      run: |
        ipython -c "%run code/request_rnwf.ipynb"

    - name: Move CSV File to Data Folder
      run: |
        mv rnwf_data/rnwf.csv rnwf_data/$(date +%Y-%m-%d)/

    - name: Commit files
      run: |
          git add rnwf_data/*
          git commit -am "RNWF data Update $(date)"
          git push origin main


